name: Deploy to Cloudflare Worker

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - Cargo.*
      - flake.*
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install worker-build
        run: cargo install worker-build
      - name: Deploy to Cloudflare Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          CONFIG: ${{ secrets.CONFIG }}
          RUSTFLAGS: --cfg getrandom_backend="wasm_js"
